### ISSUE TITLE
day01

### ISSUE THREAD

**Issue by wxdland** [algorithm008-class02/algorithm008-class02#4]
#学号：G20200343050218
#姓名：邬湘东
#班级：2班
#小组：勤学好问组
#作业&总结链接：https://github.com/wxdland/algorithm008-class02/tree/master/Week_01

**Comment by wangbaobiao** [comment]
#学号：G20200343050128
#姓名：wangbaobiao
#班级：2班
#小组：勤学好问组, 刷题狂魔组
#作业&总结链接：https://github.com/wangbaobiao/algorithm008-class02/tree/master/Week_01
