### ISSUE TITLE
G20200343050208-第二周作业

### ISSUE THREAD

**Issue by yanwenxian** [algorithm008-class02/algorithm008-class02#42]
#学号:G20200343050208
#姓名:颜文娴
#班级:算法8期2班
#小组:Java组
#作业&总结链接：https://github.com/yanwenxian/algorithm008-class02/commit/28cc637fb52362d7421909404411df5ae4a264b5

**Comment by Xiaofei07** [comment]
#学号:G20200343050046
#姓名:宋笑飞
#班级:算法8期2班
#小组:刷题狂魔
#作业&总结链接：https://github.com/Xiaofei07/algorithm008-class02/tree/master/Week_02

**Comment by Broly789** [comment]
#学号:G20200343050066
#姓名:李文利
#班级:算法8期2班
#小组:刷题狂魔 & JS组
#作业&总结链接：https://github.com/Brolly0204/algorithm008-class02/tree/master/Week_02
